server:
  port: 8080

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: player-api
          uri: lb://PLAYER-API
          predicates:
            - Path=/player/v1/**
        - id: item-api
          uri: lb://ITEM-API
          predicates:
            - Path=/item/v1/**