server:
  port: 8080
  ssl:
    key-store-password: mobywallet
    key-store-type: PKCS12
    key-store: classpath:keystore/mobywallet.p12
    key-alias: mobywallet

eureka:
  client:
    registerWithEureka: false

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: player-api
          uri: lb://player-api
          predicates:
            - Path=/player/v1/**
        - id: item-api
          uri: lb://item-api
          predicates:
            - Path=/item/v1/**